packages/api-client/src/api/getProduct/index.ts
packages/api-client/src/types.ts
packages/composables/src/getters/productGetters.ts

add prices data to product details page

Add prices to product data

---

packages/api-client/src/api/getCategory/index.ts
packages/api-client/src/api/getProduct/index.ts
packages/api-client/src/types.ts
packages/composables/src/getters/facetGetters.ts
packages/composables/src/getters/productGetters.ts
packages/composables/src/useProduct/index.ts
packages/theme/composables/useUiHelpers/index.ts
packages/theme/pages/Product.vue

Add initial Product.vue so we can add Retail components

feat: add product.vue initial setup

---

packages/api-client/src/api/getProducts/index.ts
packages/api-client/src/types.ts
packages/composables/src/getters/productGetters.ts
packages/theme/middleware.config.js

Cover image for list pages
[AB#60255](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/60255)

feat: cover image for list pages

---

packages/api-client/src/api/getProducts/index.ts
packages/composables/src/getters/facetGetters.ts
packages/theme/composables/useUiHelpers/index.ts

Implement sorting options for list pages
[AB#61068](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/61068)

feat: implement sorting options for list pages

---

packages/theme/components/SearchResults.vue

Fix adding to cart from search suggestion

fix: adding to cart from search suggestion

---

packages/theme/components/HeaderNavigation.vue

[AB#61725](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/61725)

fix: close menu when click on mobile

---

docs/guide/use-inventory.md
packages/api-client/src/api/inventoryItems/findInventoryItemStatus/index.ts
packages/api-client/src/index.server.ts
packages/api-client/src/types.ts
packages/composables/src/factories/useInventoryFactory.ts
packages/composables/src/getters/inventoryGetters.ts
packages/composables/src/getters/productGetters.ts
packages/composables/src/index.ts
packages/composables/src/types.ts
packages/composables/src/useInventory/index.ts
packages/theme/middleware.config.js
packages/theme/pages/Product.vue

Implement useInventory composable
Implement useInventory composable, inventoryGetters, demo it on Product Details page and add docs
[AB#60289](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/60289)
If product OutOfStock disable Add to Cart button on product details page
On Product Details page, disable AddToCart button for out of stock variant and also display available quantity for current product

feat: useInventory composable

---

packages/composables/src/getters/cartGetters.ts
packages/theme/components/CartSidebar.vue

[AB#61779](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/61779)

fix: hide price in cart when it is absent

---

README.md
docs/guide/configuration.md

update read-me and confguration docs

feat: update read-me and confguration docs

---

packages/api-client/src/api/membership/resetPassword/index.ts
packages/composables/src/useForgotPassword/index.ts
packages/theme/components/LoginModal.vue

fixed bug for resetting password not exist email
[AB#62160](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/62160)

fix: fixed bug for resetting password not exist email

---

packages/api-client/src/api/carts/mergeCarts/index.ts
packages/api-client/src/index.server.ts
packages/composables/src/helpers/generalUtils.ts
packages/composables/src/useCart/index.ts
packages/composables/src/useUser/index.ts

Prepare API to merge users carts by token
add API to merge two carts
[AB#62019](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/62019)
Ability to merge Guest cart after login and registration
After Login the guest  cart is merged with customer cart

feat: merge carts after login and registration

---

packages/composables/src/useUser/index.ts
packages/theme/components/MyAccount/PasswordResetForm.vue

fixed validation bug
[AB#62489](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/62489)

fix: fixed validation bug

---

docs/guide/use-wishlist.md
packages/api-client/src/api/carts/clearCart/index.ts
packages/api-client/src/api/carts/clearCartItems/index.ts
packages/api-client/src/api/carts/getCartLineItems/index.ts
packages/api-client/src/index.server.ts
packages/api-client/src/types.ts
packages/composables/src/getters/wishlistGetters.ts
packages/composables/src/helpers/wishlistUtils.ts
packages/composables/src/useWishlist/index.ts
packages/theme/components/AppHeader.vue
packages/theme/components/LoginModal.vue
packages/theme/components/RelatedProducts.vue
packages/theme/components/SearchResults.vue
packages/theme/components/WishlistSidebar.vue
packages/theme/pages/Category.vue
packages/theme/pages/MyAccount.vue
packages/theme/pages/Product.vue

Implement  add, remove, preview wishlist
implemented add, remove, preview wishlist
[AB#60285](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/60285)
[AB#60286](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/60286)
be able to add, remove items to wishlist and then preview it
click on heart icon on product

feat: implement  add, remove, preview wishlist

---

packages/theme/pages/Category.vue

fixed duplicate icon for wish list mobile
[AB#62657](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/62657)

fix: duplicate icon for wish list mobile

---

packages/composables/src/getters/cartGetters.ts
packages/composables/src/getters/wishlistGetters.ts
packages/theme/components/CartSidebar.vue
packages/theme/components/WishlistSidebar.vue

Add link to product in cart and wishlist
[AB#62705](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/62705)

fix: add link to product in wishlist and cart

---

packages/api-client/src/api/getProducts/index.ts
packages/theme/pages/Category.vue

Fix Category page bug
[AB#62802](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/62802)

fix: category page 

---

packages/theme/components/BottomNavigation.vue
packages/theme/pages/Category.vue

Fix mobile bottom navigation links
[AB#62764](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/62764)
[AB#62798](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/62798)
[AB#62229](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/62229)

fix: mobile bottom navigation links

---

packages/theme/components/CartSidebar.vue
packages/theme/components/WishlistSidebar.vue

Close wishlist and cart sidebars when click on product item
[AB#62705](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/62705)

fix: close sidebar when navigate to product

---

docs/guide/use-cart.md
docs/guide/use-countries.md
packages/api-client/src/types.ts
packages/composables/src/getters/cartGetters.ts
packages/composables/src/getters/countriesGetters.ts
packages/composables/src/types.ts
packages/theme/components/AddressPreview.vue
packages/theme/components/Checkout/CartItemsTable.vue
packages/theme/components/Checkout/CouponCode.vue
packages/theme/layouts/default.vue
packages/theme/nuxt.config.js
packages/theme/pages/Checkout/Payment.vue
packages/theme/pages/Checkout/Review.vue
packages/theme/pages/MyAccount/ShippingDetails.vue

Checkout Review Order  Step
[AB#61788](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/61788) 
Ability to review all order information befor submit
Personal details, Shipping address, Billing Address , Payment method , Items as table review on last step
On Mobile also Apply coupon is visible

feat: checkout review order step

---

docs/guide/use-cart.md
packages/api-client/src/types.ts
packages/composables/src/getters/cartGetters.ts
packages/theme/components/AddressPreview.vue
packages/theme/pages/Checkout/Payment.vue
packages/theme/pages/Checkout/Review.vue

Logic to calculate if Cart is ready for Order

feat: ready for order conditions

---

packages/api-client/src/api/carts/completeCheckout/index.ts
packages/api-client/src/index.server.ts
packages/composables/src/useMakeOrder/index.ts
packages/theme/composables/useUiHelpers/index.ts
packages/theme/pages/Checkout/Review.vue

feat: get translation helper

---

packages/composables/src/useWishlist/index.ts

first load of wishlist for quest - it was lust empty string and throw error 
[AB#63380](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/63380)

fix: first load of wishlist for quest

---

packages/theme/pages/Checkout/PersonalDetails.vue
packages/theme/pages/Checkout/Shipping.vue

Personal data are not filled out
[AB#63406](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/63406)
Unable to proceed to the next step after adding new address
[AB#63472](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/63472)
It should not be possible to proceed without selecting shipping address
[AB#63412](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/63412)
Previously created address doesn't appear after logging in 
[AB#63410](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/63410)

fix: checkout process 

---

packages/theme/components/Checkout/VsfShippingProvider.vue

Change layout for shipping method to be like this

fix: layout for shipping methods

---

packages/theme/components/Checkout/CartSaving.vue
packages/theme/pages/Checkout/Review.vue

[AB#63495](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/63495)

fix: show always savings

---

packages/theme/pages/MyAccount/OrderHistory.vue

implement order history saving fix
[AB#60287](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/60287)

feat: implement order history saving fix

---

packages/theme/pages/MyAccount/BillingDetails.vue
packages/theme/pages/MyAccount/ShippingDetails.vue

Fix load user address for new addresses
[AB#63854](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/63854)

fix: load user addresses

---

packages/composables/src/getters/cartGetters.ts
packages/theme/pages/Checkout.vue
packages/theme/pages/Checkout/Billing.vue
packages/theme/pages/Checkout/Review.vue
packages/theme/pages/Checkout/Shipping.vue

Define new steps:
Details -> Shipping -> Billing -> Review
[AB#61787](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/61787)

feat: billing step as separate step and payment on review

---

docs/guide/use-order.md
packages/api-client/src/api/orders/getOrderById/index.ts
packages/api-client/src/api/orders/getOrderByNumber/index.ts
packages/api-client/src/helpers/generalUtils.ts
packages/api-client/src/index.server.ts
packages/composables/src/getters/orderGetters.ts
packages/composables/src/useOrder/index.ts
packages/theme/lang/en.js
packages/theme/pages/Checkout/Billing.vue
packages/theme/pages/Checkout/Shipping.vue
packages/theme/pages/Checkout/ThankYou.vue
packages/theme/pages/MyAccount/OrderHistory.vue

Order Confirmation page
Implement Order Confirmation page
[AB#61983](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/61983)
Ability to submit an Order and see Thank you page.
On Checkout process, Submit Order button

feat: order thank you page

---

packages/api-client/src/types.ts
packages/composables/src/getters/cartGetters.ts
packages/theme/pages/Checkout/Billing.vue
packages/theme/pages/Checkout/Review.vue
packages/theme/pages/MyAccount/OrderHistory.vue

[AB#61787](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/61787)

fix: billing and review step for pickup method

---

packages/theme/composables/useUiState.ts

[AB#64326](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/64326)

fix: toggle mobile menu  when stores modal is open

---

packages/theme/components/AppHeader.vue
packages/theme/components/Layout/OfflineWarning.vue
packages/theme/layouts/default.vue

[AB#64070](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/64070)
move offline warning to the top and add a placeholder.

fix: offline warning to the top and add a placeholder

---

packages/theme/lang/en.js
packages/theme/lang/fr.js
packages/theme/plugins/token-expired.client.ts

[AB#63925](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/63925)

fix: show the message that token is expired and reload the page

---

jest.base.config.js
packages/api-client/src/api/carts/removeCartItems/index.ts
packages/api-client/src/index.server.ts
packages/api-client/src/types.ts
packages/composables/src/factories/useCartFactory.ts
packages/composables/src/getters/cartGetters.ts
packages/composables/src/helpers/cartUtils.spec.ts
packages/composables/src/helpers/cartUtils.ts
packages/composables/src/types.ts
packages/composables/src/useCart/index.ts
packages/theme/lang/en.js
packages/theme/pages/Checkout/Review.vue

clear cart from unavailable items
Implement a clear cart from unavailable items
[AB#64420](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/64420)
Ability to  clear cart from unavailable items
Add to cart not available item, try to clear

feat: implement clear cart from unavailable items

---

docs/guide/getting-started.md
packages/theme/nuxt.config.js

[AB#64330](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/64330)
Disable log message for workbox
Disable debug mode for workbox

fix: disable debug for workbox

---

packages/theme/pages/MyAccount/OrderHistory.vue

[AB#63974](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/63974)

fix: image on mobile for order details

---

packages/theme/components/HeaderNavigation.vue

[AB#64888](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/64888)

fix: empty mobile menu

---

packages/theme/components/AppHeader.vue
packages/theme/components/BottomNavigation.vue

[AB#65238](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/65238)

fix: open my account page when menu is opened

---

packages/theme/layouts/default.vue

[AB#64341](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/64341)
button close on wrong place

fix: add workaround for close button

---

README.md
docs/guide/configuration.md

update readme with supported features

feat: update readme with supported features

---

packages/theme/pages/Checkout/Billing.vue
packages/theme/pages/Checkout/Shipping.vue

[AB#65922](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/65922)

fix: address save on checkout

---

packages/api-client/src/api/getCategory/index.ts
packages/api-client/src/api/getProducts/index.ts
packages/composables/src/getters/categoryGetters.ts
packages/composables/src/getters/facetGetters.ts
packages/composables/src/getters/productGetters.ts
packages/theme/components/AppHeader.vue
packages/theme/components/HeaderNavigation.vue
packages/theme/components/HeaderNavigationSubcategories.vue
packages/theme/layouts/default.vue
packages/theme/pages/Category.vue

Hide categories without products

feat: hide categories without products in menu and nav tree

---

docs/guide/configuration.md
packages/api-client/src/api/carts/getPaymentMethods/index.ts
packages/composables/src/getters/paymentMethodGetters.ts
packages/theme/components/Checkout/PaymentMethods.vue
packages/theme/components/Checkout/VsfPaymentProvider.vue
packages/theme/middleware.config.js

configure payment providers in config
[AB#66243](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/66243)

feat: configure payment providers in config

---

docs/release/generate-template.md
packages/composables/src/getters/productGetters.ts
packages/theme/composables/index.ts
packages/theme/composables/useUiNotification/index.ts
packages/theme/pages/Checkout/Shipping.vue
packages/theme/plugins/token-expired.client.ts

[AB#65760](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/65760) 
Prepare for template
Documentation for creating the template

feat: 65760 pwa create script to generate template based on theme from main repository

---

.az.publish.yml

[AB#65759](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/65759)

feat: [pipeline] uncomment publish

---

.az.publish.yml

[AB#65759](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/65759)

feat: [pipeline] tag variable

---

.az.publish.yml
.github/ISSUE_TEMPLATE/1.bug-report.yml
docs/release/generate-template.md
package.json
scripts/updateTemplate.js
yarn.lock

[AB#65760](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/65760)
Build template

feat: pwa create script to generate template based on theme from main repository v2

---

.az.publish.yml
.github/ISSUE_TEMPLATE/1.bug-report.yml
GitVersion.yml
docs/release/generate-template.md
lerna.json
package.json
packages/api-client/package.json
packages/composables/package.json
packages/theme/package.json
scripts/updateTemplate.js
yarn.lock

feat: new pipiline with package creation and template generation
